"""empty message

Revision ID: 261ddbd9836a
Revises: cb6e2369063f
Create Date: 2023-01-17 05:50:57.669848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261ddbd9836a'
down_revision = 'cb6e2369063f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('readed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.drop_column('readed')

    # ### end Alembic commands ###
