"""empty message

Revision ID: 2e1f81c52d3d
Revises: 925e0b79d979
Create Date: 2023-02-05 17:41:40.534863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1f81c52d3d'
down_revision = '925e0b79d979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musical_instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('musical_instruments_category_name', sa.String(), nullable=False))
        batch_op.drop_constraint('musical_instrument_musical_instruments_category_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'musical_instruments_category', ['musical_instruments_category_name'], ['name'])
        batch_op.drop_column('musical_instruments_category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musical_instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('musical_instruments_category_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('musical_instrument_musical_instruments_category_id_fkey', 'musical_instruments_category', ['musical_instruments_category_id'], ['id'])
        batch_op.drop_column('musical_instruments_category_name')

    # ### end Alembic commands ###
