"""empty message

Revision ID: 4568c65d0567
Revises: b2310489e7f1
Create Date: 2023-02-05 17:49:46.200983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4568c65d0567'
down_revision = 'b2310489e7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musical_instrument', schema=None) as batch_op:
        batch_op.drop_constraint('musical_instrument_name_key', type_='unique')
        batch_op.drop_column('creation_date')
        batch_op.drop_column('last_update')

    with op.batch_alter_table('musical_instruments_category', schema=None) as batch_op:
        batch_op.drop_constraint('musical_instruments_category_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musical_instruments_category', schema=None) as batch_op:
        batch_op.create_unique_constraint('musical_instruments_category_name_key', ['name'])

    with op.batch_alter_table('musical_instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('musical_instrument_name_key', ['name'])

    # ### end Alembic commands ###
