"""empty message

Revision ID: 4729f6e2c722
Revises: 92596c4da857
Create Date: 2023-01-02 07:23:58.302280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4729f6e2c722'
down_revision = '92596c4da857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('img_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('img_test')
    # ### end Alembic commands ###
