"""empty message

Revision ID: 5f19c113b71e
Revises: d46ee6b328eb
Create Date: 2023-01-02 17:16:14.598246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f19c113b71e'
down_revision = 'd46ee6b328eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influence_band', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_genre_name', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('influence_band_music_genre_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'music_genre', ['music_genre_name'], ['name'])
        batch_op.drop_column('music_genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influence_band', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_genre', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('influence_band_music_genre_fkey', 'music_genre', ['music_genre'], ['name'])
        batch_op.drop_column('music_genre_name')

    # ### end Alembic commands ###
