"""empty message

Revision ID: 70f491604bf8
Revises: 7b1ec94500fc
Create Date: 2023-02-03 18:38:15.440561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f491604bf8'
down_revision = '7b1ec94500fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band_music_genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musicgenre_id', sa.Integer(), nullable=False),
    sa.Column('bands_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bands_id'], ['bands.id'], ),
    sa.ForeignKeyConstraint(['musicgenre_id'], ['music_genre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('band_music_genre')
    # ### end Alembic commands ###
