"""empty message

Revision ID: 7b1ec94500fc
Revises: f9abbb259ccb
Create Date: 2023-02-02 18:33:05.192132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1ec94500fc'
down_revision = 'f9abbb259ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('local_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('local_music_genre', schema=None) as batch_op:
        batch_op.alter_column('local_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_music_genre', schema=None) as batch_op:
        batch_op.alter_column('local_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('local_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
