"""empty message

Revision ID: 808fdc9775dd
Revises: 4729f6e2c722
Create Date: 2023-01-02 07:43:51.563453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808fdc9775dd'
down_revision = '4729f6e2c722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('img_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('img_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('img_size', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('img_test', schema=None) as batch_op:
        batch_op.drop_column('img_size')
        batch_op.drop_column('img_type')
        batch_op.drop_column('img_name')

    # ### end Alembic commands ###
