"""empty message

Revision ID: 92596c4da857
Revises: cba646cabc61
Create Date: 2022-12-31 10:58:20.034112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92596c4da857'
down_revision = 'cba646cabc61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
