"""empty message

Revision ID: 925e0b79d979
Revises: d6a6e4963368
Create Date: 2023-02-05 08:40:11.479428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925e0b79d979'
down_revision = 'd6a6e4963368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bands', schema=None) as batch_op:
        batch_op.drop_constraint('bands_description_key', type_='unique')
        batch_op.drop_constraint('bands_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bands', schema=None) as batch_op:
        batch_op.create_unique_constraint('bands_name_key', ['name'])
        batch_op.create_unique_constraint('bands_description_key', ['description'])

    # ### end Alembic commands ###
