"""empty message

Revision ID: 982c7776f4b0
Revises: f0007b561f1c
Create Date: 2023-01-21 15:37:04.867149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982c7776f4b0'
down_revision = 'f0007b561f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('local_music_genre')
    with op.batch_alter_table('music_genre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'local', ['local_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_genre', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('local_id')

    op.create_table('local_music_genre',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('musicgenre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('local_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['local.id'], name='local_music_genre_local_id_fkey'),
    sa.ForeignKeyConstraint(['musicgenre_id'], ['music_genre.id'], name='local_music_genre_musicgenre_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='local_music_genre_pkey')
    )
    # ### end Alembic commands ###
