"""empty message

Revision ID: b2310489e7f1
Revises: 2e1f81c52d3d
Create Date: 2023-02-05 17:43:33.908340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2310489e7f1'
down_revision = '2e1f81c52d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musical_instrument', schema=None) as batch_op:
        batch_op.alter_column('creation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('last_update',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musical_instrument', schema=None) as batch_op:
        batch_op.alter_column('last_update',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('creation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
