"""empty message

Revision ID: b592345d363c
Revises: 8bc53a8a09c8
Create Date: 2023-01-02 17:38:56.751540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b592345d363c'
down_revision = '8bc53a8a09c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influence_band', schema=None) as batch_op:
        batch_op.drop_constraint('influence_band_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influence_band', schema=None) as batch_op:
        batch_op.create_unique_constraint('influence_band_name_key', ['name'])

    # ### end Alembic commands ###
