"""empty message

Revision ID: d46ee6b328eb
Revises: 808fdc9775dd
Create Date: 2023-01-02 17:08:33.371870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46ee6b328eb'
down_revision = '808fdc9775dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influence_band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('music_genre', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['music_genre'], ['music_genre.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('influence_band')
    # ### end Alembic commands ###
