"""empty message

Revision ID: e92bc8bdbfa1
Revises: daf4787f506e
Create Date: 2023-01-08 11:17:21.949391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92bc8bdbfa1'
down_revision = 'daf4787f506e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locales', schema=None) as batch_op:
        batch_op.alter_column('city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('locales_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('locales_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.alter_column('city_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
