"""empty message

Revision ID: eef874dfbd60
Revises: f0221d9faaa0
Create Date: 2023-01-06 17:58:22.203733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eef874dfbd60'
down_revision = 'f0221d9faaa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musical_instrument', schema=None) as batch_op:
        batch_op.alter_column('last_update',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('creation_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musical_instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.alter_column('last_update',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
