"""empty message

Revision ID: f0221d9faaa0
Revises: 617ebbc0a6a1
Create Date: 2023-01-06 17:55:46.517193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0221d9faaa0'
down_revision = '617ebbc0a6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musical_instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('musical_instruments_category_name', sa.String(), nullable=False))
        batch_op.drop_constraint('musical_instrument_name_key', type_='unique')
        batch_op.drop_constraint('musical_instrument_musical_instruments_category_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('musical_instrument_user_musical_instruments_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'musical_instruments_category', ['musical_instruments_category_name'], ['name'])
        batch_op.drop_column('user_musical_instruments_id')
        batch_op.drop_column('musical_instruments_category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musical_instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('musical_instruments_category_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_musical_instruments_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('musical_instrument_user_musical_instruments_id_fkey', 'user_musical_instrument', ['user_musical_instruments_id'], ['id'])
        batch_op.create_foreign_key('musical_instrument_musical_instruments_category_id_fkey', 'musical_instruments_category', ['musical_instruments_category_id'], ['id'])
        batch_op.create_unique_constraint('musical_instrument_name_key', ['name'])
        batch_op.drop_column('musical_instruments_category_name')

    # ### end Alembic commands ###
