"""empty message

Revision ID: f93d9bd8c634
Revises: 
Create Date: 2022-12-17 18:41:15.411285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93d9bd8c634'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bandas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banda_nombre', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('instrument', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('instrument')
    )
    op.create_table('locales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locales', sa.String(length=120), nullable=False),
    sa.Column('offers_jamsession', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conciertos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bandas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bandas_id'], ['bandas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('localidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('localidad', sa.String(length=120), nullable=False),
    sa.Column('provincia', sa.String(length=80), nullable=False),
    sa.Column('locales_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locales_id'], ['locales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('localidad')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('surnames', sa.String(length=80), nullable=False),
    sa.Column('user_name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('localidad_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('birth_day', sa.DateTime(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['localidad_id'], ['localidad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('bandas_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bandas_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bandas_id'], ['bandas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruments_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instruments_users')
    op.drop_table('bandas_users')
    op.drop_table('user')
    op.drop_table('localidad')
    op.drop_table('conciertos')
    op.drop_table('locales')
    op.drop_table('instruments')
    op.drop_table('bandas')
    # ### end Alembic commands ###
