"""empty message

Revision ID: f9abbb259ccb
Revises: c8f82ab8e11e
Create Date: 2023-02-02 17:57:38.585617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9abbb259ccb'
down_revision = 'c8f82ab8e11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('band_img', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'city', ['city_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bands', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('band_img')
        batch_op.drop_column('city_id')

    # ### end Alembic commands ###
